ALTER TABLE settings ADD COLUMN proxy_mode TEXT NOT NULL DEFAULT 'system';
ALTER TABLE settings ADD COLUMN proxy_host TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN proxy_port INTEGER NOT NULL DEFAULT 0;
